Repository keep-network/website, pull requests merged in 2021-04, with the labels that each got.

#356 Feat(UI)/SRT-26: Update header and footer styling
  src/components/EmailForm.js
  src/components/FeatureCarousel.js
  src/components/Footer.js
  src/components/Header.js
  src/components/SubmitButton.js
  src/components/SummaryGrid.js
  src/css/button.scss
  src/css/footer.scss
  src/css/forms.scss
  src/css/header.scss
  src/css/home.scss
Labels: ready for review

#361 feat(data)/srt-18: data modeling for Build page
  src/constants.js
  src/pages/build.md
  src/templates/build-page.js
  static/admin/config.yml
  static/images/build.png
  static/images/features/all-the-keeps.png
  static/images/features/keep-stats.png
  static/images/features/keep-tools.png
  static/images/svg/ic-design-system.svg
  static/images/svg/ic-github.svg
  static/images/svg/ic-secure-built.svg
  static/images/svg/ic-tech-doc.svg
Labels: ready for review, ready to merge

#363 feat(data)/srt-21: data modeling for FAQ page
  src/pages/faq.md
  src/templates/faq-page.js
  static/admin/config.yml
  static/images/ic-plus.png
  static/images/svg/ic-plus.svg
Labels: ready for review, ready to merge

#365 feat(data)/SRT-19: data modeling for Team page
  src/components/Profile.js
  src/header/nav.md
  src/pages/team.md
  src/templates/team-page.js
  static/admin/config.yml
  static/images/beau-bw.png
  static/images/chris-bw.png
  static/images/doug-bw.png
  static/images/kris-bw.png
  static/images/michal-bw.png
  static/images/michalina-bw.png
  static/images/tomasz-bw.png
  static/images/will-bw.png
Labels: ready for review

#367 Feat(UI)/SRT-4: Create build page
  src/components/FeatureCarousel.js
  src/css/app.scss
  src/css/build.scss
  src/css/home.scss
  src/css/utilities.scss
  src/templates/build-page.js
  static/images/svg/green-rect.svg
Labels: ready for review

#371 feat(UI)/SRT-30: Separate Page & Components styling
  src/components/Button.js
  src/components/Contact.js
  src/components/EmailForm.js
  src/components/FeatureCard.js
  src/components/Header.js
  src/components/index.js
  src/css/app.scss
  src/css/button.scss
  src/css/feature-card.scss
  src/css/forms.scss
  src/css/home.scss
  src/css/info.scss
  src/css/typography.scss
  src/pages/info.md
  src/templates/info-page.js
Labels: ready to merge

#369 feat(UI)/SRT-3: UI styling for Info page
  src/components/Contact.js
  src/components/EmailForm.js
  src/components/index.js
  src/css/app.scss
  src/css/button.scss
  src/css/home.scss
  src/css/info.scss
  src/pages/info.md
  src/templates/info-page.js
Labels: ready to merge

#373 feat(UI)/SRT-25: Header & Footer UI styling with Mobile responsive
  src/components/CollapsibleList.js
  src/components/Header.js
  src/components/Icons.js
  src/css/button.scss
  src/css/footer.scss
  src/css/header.scss
  src/css/home.scss
Labels: ready for review

#376 Feat(UI)/SRT-6: UI styling for New-Press Page
  src/css/press.scss
  src/templates/press-page.js
Labels: ready for review

#377 hotfix(lint): fixed lint error in Press page
  src/templates/press-page.js
Labels: ready for review

#370 feat(UI)/SRT-9: Stake page UI styling
  src/components/RecommendedCard.js
  src/components/WhyStakeCard.js
  src/css/app.scss
  src/css/stake-page.scss
  src/templates/stake-page.js
Labels: ready to merge

#378 hotfix(lint): fixed lint errors in Stake page
  src/components/RecommendedCard.js
  src/components/WhyStakeCard.js
  src/templates/stake-page.js
Labels: ready for review

#374 Feat(UI)/SRT-5: Create team page
  src/components/Profile.js
  src/css/app.scss
  src/css/blurb.scss
  src/css/profile.scss
  src/css/team.scss
  src/templates/team-page.js
Labels: ready to merge

#379 Hotfix(build): fixed build error in Stake page
  src/components/RecommendedCard.js
  src/components/WhyStakeCard.js
Labels: ready for review

#380 Feat(UI)/SRT-31: [WIP] General review for Landing page
  src/components/Contact.js
  src/components/Header.js
  src/components/SummaryGrid.js
  src/css/footer.scss
  src/css/header.scss
  src/css/home.scss
  src/css/page-section.scss
  src/css/typography.scss
  src/templates/home-page.js
Labels: ✨ enhancement

#381 Hotfix(Build): Fixed build error in Header
  src/components/Header.js
Labels: ready for review

#382 Feat(UI)/SRT-34: Landing Page UI fixes
  src/css/home.scss
Labels: ready for review

#384 feat(UI)/SRT-34/Landing page and all pages hero title spacing fixed
  src/css/build.scss
  src/css/info.scss
  src/css/page-section.scss
  src/css/press.scss
  src/css/team.scss
  src/templates/build-page.js
  src/templates/press-page.js
  src/templates/stake-page.js
Labels: ready for review

#385 feat(UI)/SRT-35/FAQ page answers styled and set to actual answers
  src/css/faq.scss
  src/pages/faq.md
  src/templates/faq-page.js
Labels: ready for review

#386 Bug/SRT-39: Fix Build Error - Fixed
  .eslintrc
  src/templates/build-page.js
  src/templates/faq-page.js
  src/templates/stake-page.js
Labels: ready for review

#383 Feat(UI)/SRT-36: News-Press
  src/css/press.scss
  src/templates/press-page.js
Labels: ready for review

#387 feat(UI)/SRT-32: General Review Part 2
  .prettierrc
  src/components/KeepBlog.js
  src/components/MiniLogoWall.js
  src/components/SummaryGrid.js
  src/css/app.scss
  src/css/contact.scss
  src/css/home.scss
  src/css/keep-blog.scss
  src/css/legal.scss
  src/css/minilogo-grid.scss
  src/css/page-section.scss
  src/css/profile.scss
  src/css/summary-grid.scss
  src/pages/index.md
  src/templates/home-page.js
Labels: ready for review

#389 feat(UI)/SRT-37: Refactor styling
  src/components/CollapsibleList.js
  src/components/KeepBlog.js
  src/components/Profile.js
  src/components/RecommendedCard.js
  src/components/SubmitButton.js
  src/components/WhyStakeCard.js
  src/constants.js
  src/css/app.scss
  src/css/build.scss
  src/css/collapsible-list.scss
  src/css/contact.scss
  src/css/exchanges.scss
  src/css/faq.scss
  src/css/header.scss
  src/css/home.scss
  src/css/info.scss
  src/css/keep-blog.scss
  src/css/press.scss
  src/css/profile.scss
  src/css/stake-page.scss
  src/css/team.scss
  src/pages/press.md
  src/templates/build-page.js
  src/templates/faq-page.js
  src/templates/info-page.js
  src/templates/press-page.js
  src/templates/stake-page.js
  src/templates/team-page.js
  static/images/svg/green-rect.svg
  static/images/svg/ic-close.svg
Labels: ready for review

#390 Feat(UI)/SRT-42: News-Press page filters fixed
  src/css/press.scss
  src/templates/press-page.js
Labels: ready for review

#391 Feat(UI)/SRT-44: Functionality - News-Press latest coverage
  src/css/press.scss
  src/templates/press-page.js
Labels: ready for review

#393 feat(UI)/SRT-43: Header animation
  src/components/Header.js
  src/css/header.scss
Labels: ready for review

#394 Feat(UI)/SRT-38: UI Landing page keep solution baseline parallax
  package-lock.json
  package.json
  src/templates/home-page.js
Labels: ready for review

#395 Feat(UI)/SRT-41: UI Landing page keep solution parallax updates
  src/css/home.scss
  src/templates/home-page.js
Labels: ready for review

#397 Hotfix(UI)/SRT-48: Header update
  src/constants.js
  src/css/header.scss
  src/css/home.scss
  src/templates/home-page.js
Labels: ready for review

#398 Feat(UI)/SRT-49: UI Landing page keep solution parallax updates 2
  src/css/home.scss
  src/templates/home-page.js
Labels: ready for review

#399 Feat(UI)/SRT-62: Keep animation - landing page - keep solution ui
  src/templates/home-page.js
Labels: ready for review
