Repository keep-network/website, pull requests merged in 2021-06, with the labels that each got.

#446 Fix(UI)/SRT-87: UI feedback update 3
  src/components/App.js
  src/components/Contact.js
  src/components/EmailForm.js
  src/components/Header.js
  src/css/app.scss
  src/css/build.scss
  src/css/faq.scss
  src/css/feature-card.scss
  src/css/forms.scss
  src/css/header.scss
  src/css/home.scss
  src/css/info.scss
  src/css/page-section.scss
  src/css/profile.scss
  src/templates/build-page.js
  src/templates/faq-page.js
  src/templates/info-page.js
  src/templates/press-page.js
  src/templates/team-page.js
Labels: ready for review

#448 Fix/SRT-88: UI feedback update 4
  src/css/app.scss
  src/css/join.scss
  src/header/nav.md
  src/pages/index.md
  src/pages/join.md
  src/templates/home-page.js
  src/templates/join-page.js
  static/admin/config.yml
Labels: ready to merge

#457 Update Header “announcement”
  src/header/announcement.md
Labels: netlify-cms/pending_publish

#459 Update Footer “footer_nav”
  src/footer/index.md
Labels: netlify-cms/pending_publish

#460 Update Header “header_nav”
  src/header/nav.md
Labels: netlify-cms/pending_publish

#461 Update Footer “footer_nav”
  src/footer/index.md
Labels: netlify-cms/pending_publish

#462 Updates CTA to /join
  src/pages/index.md
Labels: netlify-cms/pending_publish

#463 Fixing link styles in the FAQ section
  src/pages/faq.md
Labels: netlify-cms/pending_publish

#464 Removing extra colon ":" from exchanges section
  src/pages/index.md
Labels: netlify-cms/pending_publish
