Repository keep-network/website, pull requests merged in 2021-05, with the labels that each got.

#401 Feat(UI)/SRT-67: Keep ui feedback press-page
  src/templates/press-page.js
Labels: ready for review

#402 Feat/SRT-67: Keep ui feedback build-page
  src/pages/build.md
Labels: ready for review

#403 Feat/SRT-65: Keep ui feedback stake-page
  src/css/stake-page.scss
Labels: ready for review

#404 Feat(UI)/SRT-66: Keep UI feedback team page
  src/css/blurb.scss
  src/css/profile.scss
  src/css/team.scss
  src/pages/team.md
  src/templates/team-page.js
  static/images/beau-bw.png
  static/images/chris-bw.png
  static/images/features/btn-team-banner.png
  static/images/headshots/axel.jpg
  static/images/headshots/brayton.jpg
  static/images/kris-bw.png
  static/images/michal-bw.png
  static/images/will-bw.png
Labels: ready for review

#405 Feat(UI)/SRT-68: Keep UI feedback info-page
  src/css/info.scss
  static/images/features/info-grid.png
  static/images/features/lock.png
Labels: ready for review

#406 Feat(UI)/SRT-70: Keep UI feedback stake/team page images
  src/css/stake-page.scss
  src/css/team.scss
  src/templates/stake-page.js
  src/templates/team-page.js
Labels: ready for review

#407 Feat(UI)/SRT-71: Keep UI feedback add missing images
  static/images/logos/distributedCapitalPartnersLogo.png
Labels: ready for review

#408 feat(Data)/SRT-72: UI Feedback -> All News Create Data Models
  src/pages/index.md
  src/pages/press.md
  static/admin/config.yml
Labels: ready for review

#417 Feat(UI)/SRT-78: Keep fix build error
  src/components/Button.js
  src/components/FeatureCard.js
  src/templates/stake-page.js
Labels: ready for review

#419 Feat(UI)/SRT-73: Keep UI feedback info-page missing image
  src/css/info.scss
  src/images/info-grid-mobile.png
  src/templates/info-page.js
Labels: ready for review

#420 Feat(UI)/SRT-79: Keep UI feedback stake-page pixelated image
  src/templates/stake-page.js
  static/images/svg/ic-blockdaemon.svg
Labels: ready for review

#421 feat(UI)/SRT-76: General UI Review + Code cleanup
  src/components/Header.js
  src/css/alerts.scss
  src/css/blurb.scss
  src/css/button.scss
  src/css/exchanges.scss
  src/css/forms.scss
  src/css/home.scss
  src/css/page-section.scss
  src/css/press.scss
  src/css/profile.scss
  src/css/team.scss
  src/css/typography.scss
  src/templates/home-page.js
Labels: ready for review

#422 Feat(UI)/SRT-75: Keep general UI review and code cleanup
  src/css/info.scss
  src/css/stake-page.scss
  src/templates/info-page.js
  src/templates/stake-page.js
  static/images/doug-bw.png
Labels: ready for review

#423 hotfix(UI)/SRT-81: Main Alert Behavior
  src/css/alerts.scss
Labels: ready for review

#424 Feat(UI)/SRT-80: Keep header menu underline
  src/css/header.scss
Labels: ready for review

#425 hotfix(UI)/SRT-76: General UI Review - Team page
  src/css/blurb.scss
  src/css/profile.scss
  src/css/team.scss
Labels: ready for review

#426 Feat(UI)/SRT-82: Keep UI feedback landing-page
  src/components/Contact.js
  src/components/Header.js
  src/css/forms.scss
  src/css/home.scss
  src/images/w-image.svg
Labels: ready for review

#427 feat(UI)/SRT-83: General Link Review
  src/components/Button.js
  src/components/FeatureCarousel.js
  src/components/Header.js
  src/components/KeepBlog.js
  src/components/Link.js
  src/components/MiniLogoWall.js
  src/components/PageSection.js
  src/components/Profile.js
  src/components/SummaryGrid.js
  src/components/index.js
  src/pages/press.md
  src/templates/home-page.js
  src/templates/stake-page.js
Labels: ready to merge

#428 feat(UI)/SRT-84: Links update from Design
  src/pages/build.md
  src/pages/info.md
  src/pages/stake.md
Labels: ready for review

#429 feat(Data)/SRT-85: News data update
  src/pages/press.md
  src/templates/press-page.js
Labels: ready for review

#430 hotfix/SRT-85: update blog images from design
  src/css/keep-blog.scss
  src/pages/index.md
  src/pages/press.md
  static/images/blog/coindesk-blog.png
  static/images/blog/cointelegraph.png
  static/images/blog/the-block.png
Labels: ready for review

#432 hotfix/SRT-86: News update part 2
  src/pages/index.md
  src/pages/press.md
Labels: ready for review

#434 Update Pages “team”
  src/pages/team.md
Labels: netlify-cms/pending_publish

#436 Update Pages “stake”
  src/pages/stake.md
Labels: netlify-cms/pending_publish

#437 Update Pages “build”
  src/pages/build.md
Labels: netlify-cms/pending_publish

#438 Update Pages “info”
  src/pages/info.md
Labels: netlify-cms/pending_publish

#439 Update Pages “team”
  src/pages/team.md
  static/images/sasha-bw.png
Labels: netlify-cms/pending_publish

#455 Fix discord/blog link on Info page
  src/pages/info.md
Labels: netlify-cms/pending_publish
